"""Init

Revision ID: dfbe1de0090c
Revises: 
Create Date: 2024-10-24 11:04:14.236632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfbe1de0090c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('model_used', sa.String(length=64), nullable=True),
    sa.Column('source_dataset', sa.String(length=64), nullable=True),
    sa.Column('is_revision', sa.Boolean(), nullable=True),
    sa.Column('revised_prompt_id', sa.Integer(), nullable=True),
    sa.Column('revision_author_type', sa.String(length=10), nullable=True),
    sa.Column('revision_author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reference_prompt_prefix', sa.Text(), nullable=True),
    sa.Column('flagged_for_conversation', sa.Boolean(), nullable=True),
    sa.Column('postfix', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['prompt.id'], name=op.f('fk_prompt_parent_id_prompt')),
    sa.ForeignKeyConstraint(['revised_prompt_id'], ['prompt.id'], name=op.f('fk_prompt_revised_prompt_id_prompt')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt'))
    )
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_source_id'), ['source_id'], unique=False)

    op.create_table('reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_link', sa.String(length=256), nullable=True),
    sa.Column('reference_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reference'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('interface_language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('evaluation_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], name=op.f('fk_evaluation_task_prompt_id_prompt')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_task'))
    )
    op.create_table('prompt_references',
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], name=op.f('fk_prompt_references_prompt_id_prompt')),
    sa.ForeignKeyConstraint(['reference_id'], ['reference.id'], name=op.f('fk_prompt_references_reference_id_reference')),
    sa.PrimaryKeyConstraint('prompt_id', 'reference_id', name=op.f('pk_prompt_references'))
    )
    op.create_table('rank_revise_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('extension1_id', sa.Integer(), nullable=False),
    sa.Column('extension2_id', sa.Integer(), nullable=False),
    sa.Column('extension3_id', sa.Integer(), nullable=False),
    sa.Column('extension4_id', sa.Integer(), nullable=False),
    sa.Column('ranking', sa.String(length=4), nullable=True),
    sa.Column('revised_prompt_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['extension1_id'], ['prompt.id'], name=op.f('fk_rank_revise_task_extension1_id_prompt')),
    sa.ForeignKeyConstraint(['extension2_id'], ['prompt.id'], name=op.f('fk_rank_revise_task_extension2_id_prompt')),
    sa.ForeignKeyConstraint(['extension3_id'], ['prompt.id'], name=op.f('fk_rank_revise_task_extension3_id_prompt')),
    sa.ForeignKeyConstraint(['extension4_id'], ['prompt.id'], name=op.f('fk_rank_revise_task_extension4_id_prompt')),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], name=op.f('fk_rank_revise_task_prompt_id_prompt')),
    sa.ForeignKeyConstraint(['revised_prompt_id'], ['prompt.id'], name=op.f('fk_rank_revise_task_revised_prompt_id_prompt')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_rank_revise_task_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rank_revise_task'))
    )
    op.create_table('ranking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_ranking_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ranking'))
    )
    op.create_table('ranking_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_prompt_id', sa.Integer(), nullable=False),
    sa.Column('prompt_ids', sa.PickleType(), nullable=True),
    sa.Column('ranking', sa.PickleType(), nullable=True),
    sa.Column('revised_prompt_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_prompt_id'], ['prompt.id'], name=op.f('fk_ranking_task_parent_prompt_id_prompt')),
    sa.ForeignKeyConstraint(['revised_prompt_id'], ['prompt.id'], name=op.f('fk_ranking_task_revised_prompt_id_prompt')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_ranking_task_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ranking_task'))
    )
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['evaluation_task.id'], name=op.f('fk_evaluation_task_id_evaluation_task')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_evaluation_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation'))
    )
    op.create_table('ranking_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ranking_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('rank_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ranking_id'], ['ranking.id'], name=op.f('fk_ranking_item_ranking_id_ranking')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ranking_item'))
    )
    op.create_table('ranking_items',
    sa.Column('ranking_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('rank_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ranking_id'], ['ranking.id'], name=op.f('fk_ranking_items_ranking_id_ranking')),
    sa.PrimaryKeyConstraint('ranking_id', 'item_id', name=op.f('pk_ranking_items'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ranking_items')
    op.drop_table('ranking_item')
    op.drop_table('evaluation')
    op.drop_table('ranking_task')
    op.drop_table('ranking')
    op.drop_table('rank_revise_task')
    op.drop_table('prompt_references')
    op.drop_table('evaluation_task')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('reference')
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_source_id'))

    op.drop_table('prompt')
    # ### end Alembic commands ###
